Repository anchovycation/pingu-front-end, pull requests merged in 2022-03, with the labels that each got.

#35 fix join error when user create room
  src/Pages/CreateRoom/CreateRoom.jsx
  src/Pages/JoinRoomChecker/JoinRoomChecker.jsx
Labels: bug

#36 room name dynamically displayed
  src/Pages/JoinRoomChecker/JoinRoomChecker.jsx
  src/Pages/WatchingRoom/WatchingRoom.jsx
Labels: ready for review

#32 YouTube player added
  package-lock.json
  package.json
  src/Components/YouTubePlayer/YouTubePlayer.jsx
  src/Components/YouTubePlayer/YouTubePlayer.scss
  src/Constants/SocketEvents.js
  src/Pages/JoinRoomChecker/JoinRoomChecker.jsx
  src/Pages/WatchingRoom/WatchingRoom.jsx
  yarn.lock
Labels: enhancement, ready for review
